config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'
  # API
  namespace :api, defaults: {format: :json} do
      namespace :v1 do
        resources :products
      end
  end

  root 'home#index'
  devise_for :users

  namespace :admin do
    root "home#index", as: 'root'
    resources :products
    resources :orders, only: [:index]
    resources :users, only: [:index, :show, :update, :edit]
  end

  resources :products, param: :permalink do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  resources :orders
  resources :items, only: [:update, :destroy], controller: "cart_items"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items, source: :product


  def clean!
    cart_items.destroy_all
  end

  def add(product)
    ci = cart_items.build
    ci.product = product
    ci.save
  end

  def total_price
    cart_items.map(&:total).sum
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def price
    product.price
  end

  def total
    (quantity * product.price).to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord

  has_secure_token

  belongs_to :user
  has_one  :info,  class_name: "OrderInfo", dependent: :destroy
  has_many :items, class_name: "OrderItem", dependent: :destroy

  accepts_nested_attributes_for :info, reject_if: :all_blank

  def build_item_cache_from_cart(cart)
    cart.items.each do |cart_item|
      item = items.build
      item.product_name = cart_item.title
      item.quantity = 1
      item.price = cart_item.price
      item.save
    end
  end

  def calculate_total!(cart)
    self.total = cart.total_price
    self.save
  end
end

app/models/order_info.rb
class OrderInfo < ApplicationRecord
  belongs_to :order
  validates :order, presence: true

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :cover_image, ProductImageUploader
  has_many :product_images, dependent: :destroy
  validates :title, :description, :cost, :price, presence: true

  scope :hosttest, ->{ order(score: :desc).limit(10) }
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  mount_uploader :image, ProductImageUploader
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:guest, :operator, :admin]
  has_many :orders
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController

  layout 'admin'
  before_action :authenticate_user!

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::AdminController

  def index; end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController

  def index
    @orders = Order.all.page params[:page]
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController

  before_action :set_product, only: [:edit, :show, :destroy, :update]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def update
    if Product.update(product_params)
      redirect_to admin_products_path, :flash=>{ :notice => '修改成功'}
    else
      render :new, :flash=>{ :notice => '修改失敗'}
    end
  end

  def create
    if Product.create!(product_params)
      redirect_to admin_products_path, :flash=>{ :notice => '新增成功'}
    else
      render :new, :flash=>{ :notice => '新增失敗'}
    end
  end

  def edit; end

  def show; end

  def destroy
    @product.destroy
    redirect_to admin_products_path, :flash=>{ :notice => '刪除成功'}
  end


  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :cost, :price, :cover_image, :tag, :display, :permalink)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  def index
    @users = User.all.page(params[:page])
  end
end

app/controllers/api/v1/products_controller.rb
module Api
  module V1
    class ProductsController < ApplicationController

      skip_before_filter :verify_authenticity_token
      respond_to :json

      def index
        respond_with(Product.all)
      end

      def show
        @product = Product.find(params[:id])
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_cart

  def current_cart
    @current_cart ||= find_cart
  end

  private

  def find_cart
    cart = Cart.find_by(id: session[:cart_id])

    unless cart.present?
      cart = Cart.create
    end

    session[:cart_id] = cart.id
    cart
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  before_action :authenticate_user!

  def destroy
    @cart = current_cart
    @item = @cart.cart_items.find_by(product_id: params[:id])
    @product = @item.product
    @item.destroy
    flash[:warning] = "成功將 #{@product.title} 從購物車刪除!"
  end

  def update
    @item = current_cart.cart_items.find_by(product_id: params[:cart_item][:product_id])
    @item.update(cart_item_params)
  end


  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!, only: [:checkout]

  def checkout
    @order = current_user.orders.build
    @info = @order.build_info
  end

  def clean
    current_cart.clean!
    flash[:warning] = "已清空購物車"
    redirect_to carts_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @products = Product.all
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders =  Order.where(user_id: current_user.id)
  end

  def create
    @order =  current_user.orders.build
    if @order.save
      # TO FIX
      # when use current_user.orders.build(set_params) , @order.save will throw validate fail
      # because info validate order id is empty
      @order.update(set_params)
      @order.build_item_cache_from_cart(current_cart)
      @order.calculate_total!(current_cart)
      current_cart.delete
      #OrderMailMailer.notify(@order).deliver_now!
      SendMailJob.perform_later(@order)
      redirect_to orders_path
    else
      render "carts/checkout"
    end
  end

  private

  def set_params
    params.require(:order).permit(info_attributes: [:billing_name,
                                  :billing_address,
                                  :billing_tel,
                                  :shipping_name,
                                  :shipping_address,
                                  :shipping_tel] )
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product


  def index
    @products = Product.all
  end

  def show
    @product.increment!(:score)
  end

  def add_to_cart
   current_cart.add(@product) unless current_cart.items.include?(@product)
   redirect_to :back
  end


  private

  def set_product
    @product =  Product.find_by(permalink: params[:permalink])
  end

end

app/helpers/admin/product_helper.rb
module Admin::ProductHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_cart_items_count(cart)
    cart.cart_items.count
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product], html: {multipart:  true} do |f| %>

  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: '標題'  %>
  </div>

  <div class="form-group">
    <%= f.text_area :description, class: 'form-control', placeholder: '描述'   %>
  </div>

  <div class="form-group">
    <%= f.text_field :permalink, class: 'form-control', placeholder: 'permalink'   %>
  </div>

  <div class="form-group">
    <%= f.text_field :cost, class: 'form-control', placeholder: '成本價'   %>
  </div>

  <div class="form-group">
    <%= f.text_field :price, class: 'form-control', placeholder: '售價'   %>
  </div>

  <div class="form-inline">
    <%= f.label("照片") %>
    <%= f.file_field :cover_image %>
  </div>
  <div class="form-group">
    <%= f.label("tags") %>
    <%= f.text_field :tag, class: 'form-control', 'data-role'=>"tagsinput"  %>
  </div>
  <div class="form-inline">
    <%= f.label("是否顯示") %>
    <%= f.check_box :display %>
  </div>
 <%= f.submit "送出", class: 'btn btn-primary'%>
<% end %>

app/views/admin/products/edit.html.erb
<h1>修改產品</h1>
<%= render partial: 'form' %>

app/views/admin/products/index.html.erb
<%= link_to "New", new_admin_product_path, class: 'btn btn-primary'%>
<table class="table table-hover">
  <thead>
    <tr>
      <th width="150">image</th>
      <th width="150">產品名稱</th>
      <th>描述</th>
      <th>成本</th>
      <th>售價</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product|%>
    <tr>
      <td><%= image_tag product.cover_image.url(:thumb)%></td>
      <td><%= product.title %></td>
      <td><%= product.description%></td>
      <td><%= product.try(:cost)%></td>
      <td><%= product.try(:price)%></td>
      <td>
        <%= link_to "修改", edit_admin_product_path(product.id) %>
        <%= link_to "刪除",admin_product_path(product.id), method: :delete, data: { confirm: 'are you sure'} %>

      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h1>新增產品</h1>
<%= render partial: 'form' %>

app/views/products/index.html.erb
<div class="row text-center">
  <% @products.each do |p|%>
    <div class="col-md-3 col-sm-6">
      <div class="thumbnail">
        <%= image_tag p.cover_image.url(:cover)%>
        <div class='caption'>
          <h3><%= p.title%></h3>
          <p><%= p.description%></p>
          <p>
         <%= link_to("加入購物車", add_to_cart_product_path(p.permalink), method: :post, class: "btn btn-primary") %>
         <%= link_to("產品說明",  product_path(p.permalink), class: "btn btn-default") %>
          </p>
      </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <% if @product.cover_image.present? %>
      <%= image_tag(@product.cover_image.url(:cover), class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2> <%= @product.title %> </h2>
    <div style="height:170px;">
      <p>
      <%= @product.description %>
      </p>
    </div>
    <div class="product-price"> $ <%= @product.price %> </div>
    <div class="pull-left">
      <%= link_to("加入購物車", add_to_cart_product_path(@product.permalink), method: :post, class: "btn btn-primary") %>
    </div>
  </div>
</div>