config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq'
  # API
  namespace :api, defaults: {format: :json} do
      namespace :v1 do
        resources :products
      end
  end

  root 'home#index'
  devise_for :users

  namespace :admin do
    root "home#index", as: 'root'
    resources :products
    resources :orders, only: [:index]
    resources :users, only: [:index, :show, :update, :edit]
  end

  resources :products, param: :permalink do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end

  resources :orders
  resources :items, only: [:update, :destroy], controller: "cart_items"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items, source: :product


  def clean!
    cart_items.destroy_all
  end

  def add(product)
    ci = cart_items.build
    ci.product = product
    ci.save
  end

  def total_price
    cart_items.map(&:total).sum
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def price
    product.price
  end

  def total
    (quantity * product.price).to_i
  end
end

app/models/order.rb
class Order < ApplicationRecord

  has_secure_token

  belongs_to :user
  has_one  :info,  class_name: "OrderInfo", dependent: :destroy
  has_many :items, class_name: "OrderItem", dependent: :destroy

  accepts_nested_attributes_for :info, reject_if: :all_blank

  def build_item_cache_from_cart(cart)
    cart.items.each do |cart_item|
      item = items.build
      item.product_name = cart_item.title
      item.quantity = 1
      item.price = cart_item.price
      item.save
    end
  end

  def calculate_total!(cart)
    self.total = cart.total_price
    self.save
  end
end

app/models/order_info.rb
class OrderInfo < ApplicationRecord
  belongs_to :order
  validates :order, presence: true

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :cover_image, ProductImageUploader
  has_many :product_images, dependent: :destroy
  validates :title, :description, :cost, :price, presence: true

  scope :hosttest, ->{ order(score: :desc).limit(10) }
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  mount_uploader :image, ProductImageUploader
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:guest, :operator, :admin]
  has_many :orders
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController

  layout 'admin'
  before_action :authenticate_user!

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::AdminController

  def index; end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController

  def index
    @orders = Order.all.page params[:page]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  def index
    @users = User.all.page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_cart

  def current_cart
    @current_cart ||= find_cart
  end

  private

  def find_cart
    cart = Cart.find_by(id: session[:cart_id])

    unless cart.present?
      cart = Cart.create
    end

    session[:cart_id] = cart.id
    cart
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  before_action :authenticate_user!

  def destroy
    @cart = current_cart
    @item = @cart.cart_items.find_by(product_id: params[:id])
    @product = @item.product
    @item.destroy
    flash[:warning] = "成功將 #{@product.title} 從購物車刪除!"
  end

  def update
    @item = current_cart.cart_items.find_by(product_id: params[:cart_item][:product_id])
    @item.update(cart_item_params)
  end


  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!, only: [:checkout]

  def checkout
    @order = current_user.orders.build
    @info = @order.build_info
  end

  def clean
    current_cart.clean!
    flash[:warning] = "已清空購物車"
    redirect_to carts_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @products = Product.all
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders =  Order.where(user_id: current_user.id)
  end

  def create
    @order =  current_user.orders.build
    if @order.save
      # TO FIX
      # when use current_user.orders.build(set_params) , @order.save will throw validate fail
      # because info validate order id is empty
      @order.update(set_params)
      @order.build_item_cache_from_cart(current_cart)
      @order.calculate_total!(current_cart)
      current_cart.delete
      #OrderMailMailer.notify(@order).deliver_now!
      SendMailJob.perform_later(@order)
      redirect_to orders_path
    else
      render "carts/checkout"
    end
  end

  private

  def set_params
    params.require(:order).permit(info_attributes: [:billing_name,
                                  :billing_address,
                                  :billing_tel,
                                  :shipping_name,
                                  :shipping_address,
                                  :shipping_tel] )
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product


  def index
    @products = Product.all
  end

  def show
    @product.increment!(:score)
  end

  def add_to_cart
   current_cart.add(@product) unless current_cart.items.include?(@product)
   redirect_to :back
  end


  private

  def set_product
    @product =  Product.find_by(permalink: params[:permalink])
  end

end

app/helpers/admin/product_helper.rb
module Admin::ProductHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_cart_items_count(cart)
    cart.cart_items.count
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/admin/home/index.html.erb
Admin Home Page

app/views/admin/users/index.html.erb
<div class="table-responsive">
<table class="table table-bordered">
  <thead>
    <tr class="success">
      <th>產品名稱</th>
      <th>建立時間</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user|%>
    <tr>
      <td><%= user.try(:email) %></td>
      <td><%= user.try(:created_at)%></td>
      <td>
        <%= link_to "明細", "" %>
        <%= link_to "修改", "" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
<%= paginate @users %>

app/views/application/_admin_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="/">iShop beta</a>
</div>
<!-- /.navbar-header -->

<ul class="nav navbar-top-links navbar-right">
  <li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
    <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
  </a>
  <ul class="dropdown-menu dropdown-alerts">
    <li>
    <a href="#">
      <div>
        <i class="fa fa-envelope fa-fw"></i> Message Sent
        <span class="pull-right text-muted small">4 minutes ago</span>
      </div>
    </a>
    </li>
    <li class="divider"></li>
    <li>
    <a href="#">
      <div>
        <i class="fa fa-tasks fa-fw"></i> New Task
        <span class="pull-right text-muted small">4 minutes ago</span>
      </div>
    </a>
    </li>
    <li class="divider"></li>
    <li>
    <a href="#">
      <div>
        <i class="fa fa-upload fa-fw"></i> Server Rebooted
        <span class="pull-right text-muted small">4 minutes ago</span>
      </div>
    </a>
    </li>
    <li class="divider"></li>
    <li>
    <a class="text-center" href="#">
      <strong>See All Alerts</strong>
      <i class="fa fa-angle-right"></i>
    </a>
    </li>
  </ul>
  <!-- /.dropdown-alerts -->
  </li>
  <!-- /.dropdown -->
  <li class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
  </a>
  <ul class="dropdown-menu dropdown-user">
    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
    </li>
    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
    </li>
    <li class="divider"></li>
    <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
    </li>
  </ul>
  <!-- /.dropdown-user -->
  </li>
  <!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->

<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <li>
        <%= link_to admin_orders_path do %>
          <i class="fa fa-list fa-fw"></i> Order
        <% end %>
      </li>
      <li>
        <%= link_to admin_users_path do %>
          <i class="fa fa-dashboard fa-fw"></i> User
        <% end %>
      </li>
      <li>
      <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Report<span class="fa arrow"></span></a>
      <ul class="nav nav-second-level">
        <li>
        <a href="flot.html">Flot Charts</a>
        </li>
        <li>
        <a href="morris.html">Morris.js Charts</a>
        </li>
      </ul>
      <!-- /.nav-second-level -->
      </li>
    </ul>
  </div>
  <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->
</nav>

app/views/application/_header.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">iShop</a>
  </div>
  <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/products">Products</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li class='shopping-cart hidden-xs'>
          <%= link_to carts_path do %>
            購物車
           <i class="fa fa-shopping-cart"></i>
            <span class="badge gold">
              <%= current_cart.cart_items.count %>
           </span>
          <% end %>
        </li>
      <% if !current_user %>
        <li> <%= link_to("登入", new_user_session_path) %></li>
      <% else%>
         <% if current_user.admin? %>
         <li> <%= link_to("後台", admin_root_path) %></li>
         <% end %>
        <li> <%= link_to("訂單", orders_path) %></li>
        <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %></li>
    <% end %>
    </ul>
  </div><!--/.nav-collapse -->
</div>
</nav>

app/views/carts/checkout.html.erb
<div class="row">
   <div class="col-md-12">
    <h2> 購物明細 </h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">商品明細</th>
          <th>數量</th>
          <th>單價</th>
          <th>小計</th>
        </tr>
      </thead>
      <tbody>
        <% current_cart.cart_items.each do |item| %>
          <tr>
            <td>
              <%= link_to(item.product.title, product_path(item.product)) %>
            </td>
            <td>
              <%= item.quantity %>
            </td>
            <td>
              <%= item.price %>
            </td>
            <td>
              <%= item.total %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        總計 <%= current_cart.total_price %> NTD
      </span>
    </div>

    <hr>

    <h2> 訂單資訊 </h2>

    <div class="order-form">

      <%= simple_form_for @order do |f| %>

        <%= f.simple_fields_for :info do |c| %>

          <legend> 訂購人</legend>
          <div class="form-group col-lg-4">
            <%= c.input :billing_name  %>
          </div>
          <div class="form-group col-lg-4">
            <%= c.input :billing_tel  %>
          </div>
          <div class="form-group col-lg-4">
            <%= c.input :billing_address  %>
          </div>

          <legend> 收貨人</legend>
          <div class="form-group col-lg-4">
           <%= c.input :shipping_name  %>
          </div>
          <div class="form-group col-lg-4">
           <%= c.input :shipping_tel  %>
          </div>
          <div class="form-group col-lg-4">
            <%= c.input :shipping_address  %>
          </div>
        <% end %>

        <div class="checkout">
          <%= f.submit "生成訂單", class: "btn btn-lg btn-danger pull-right",
                       data: { disable_with: "Submitting..." } %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">

    <h2> 購物車 </h2>
    <%= react_component("Cart.Index", {cart: current_cart.as_json(include: {cart_items: {include: :product}})})%>
    <br>
    <hr>
    <div class="checkout clearfix">
      <%= link_to("清除購物車", clean_carts_path, method: :delete, class: "btn btn-lg btn-default pull-right", data: { confirm: "你確定要清空整個購物車嗎？"} )%>
      <%= link_to("確認結賬", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right") %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row text-center">
  <% @products.each do |p|%>
    <div class="col-md-3 col-sm-6">
      <div class="thumbnail">
        <%= image_tag p.cover_image.url(:cover)%>
        <div class='caption'>
          <h3><%= p.title%></h3>
          <p><%= p.description%></p>
          <p>
         <%= link_to("加入購物車", add_to_cart_product_path(p.permalink), method: :post, class: "btn btn-primary") %>
         <%= link_to("產品說明",  product_path(p.permalink), class: "btn btn-default") %>
          </p>
      </div>
      </div>
    </div>
  <% end %>
</div>